mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=ergani
    - MYSQL_PASSWORD=ergani123456
    - MYSQL_DATABASE=ergani_sauron
    - MYSQL_ROOT_PASSWORD=regani
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"